# ① 利用 𝐓𝐞𝐧𝐬𝐨𝐫 创建两个大小分别 𝟑×𝟐 和 𝟒×𝟐 的随机数矩阵 𝑷 和 𝑸 ，要求服从均值为0，标准差0.01为的正态分布；② 对第二步得到的矩阵 𝑸 进行形状变换得到 𝑸 的转置 𝑸^𝑻 ；③ 对上述得到的矩阵 𝑷 和矩阵 𝑸^𝑻 求矩阵相乘

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms

### 代码实现步骤：

#### 1. 创建两个随机数矩阵 \( P \) 和 \( Q \)，它们分别服从均值为0，标准差为0.01的正态分布。
#### 2. 对矩阵 \( Q \) 进行转置操作，得到 \( Q^T \)。
#### 3. 对矩阵 \( P \) 和 \( Q^T \) 进行矩阵相乘操作。

In [2]:
import torch

# ① 创建两个矩阵 P (3×2) 和 Q (4×2)，服从均值为0，标准差为0.01的正态分布
P = torch.normal(mean=0, std=0.01, size=(3, 2))
Q = torch.normal(mean=0, std=0.01, size=(4, 2))

print("Matrix P (3×2):")
print(P)

print("\nMatrix Q (4×2):")
print(Q)

# ② 将 Q 进行转置，得到 Q^T (2×4)
Q_T = Q.t()
print("\nMatrix Q^T (2×4):")
print(Q_T)

# ③ 对矩阵 P 和 Q^T 进行矩阵相乘
result = torch.mm(P, Q_T)
print("\nResult of P × Q^T (3×4):")
print(result)

Matrix P (3×2):
tensor([[-0.0111,  0.0050],
        [ 0.0224, -0.0141],
        [ 0.0074,  0.0012]])

Matrix Q (4×2):
tensor([[ 0.0103, -0.0198],
        [-0.0084, -0.0076],
        [ 0.0129,  0.0192],
        [-0.0017,  0.0155]])

Matrix Q^T (2×4):
tensor([[ 0.0103, -0.0084,  0.0129, -0.0017],
        [-0.0198, -0.0076,  0.0192,  0.0155]])

Result of P × Q^T (3×4):
tensor([[-2.1367e-04,  5.4975e-05, -4.7197e-05,  9.5990e-05],
        [ 5.1215e-04, -7.9856e-05,  1.6895e-05, -2.5711e-04],
        [ 5.2654e-05, -7.0550e-05,  1.1729e-04,  6.0173e-06]])


### 分析：

- 首先创建了两个服从均值为0、标准差为0.01的随机矩阵 \( P \) 和 \( Q \)，分别是 \( 3 * 2 \) 和 \( 4 * 2 \) 大小。
- 接着对矩阵 \( Q \) 进行了转置操作，得到 \( Q^T \)（从 \( 4 * 2 \) 变为 \( 2 * 4 \)）。
- 最后，使用 `torch.mm` 进行矩阵相乘，得到 \( 3 * 4 \) 的结果矩阵。